#!/bin/bash

PORT=`$JOLTBIN ports new $JOLTSERVICE $JOLTNAME`

mkdir $JOLTDIR/$JOLTSERVICE-$JOLTNAME
cp mongo.monit $JOLTMONITD/$JOLTSERVICE-$JOLTNAME.monit.tmp

sed -e "s!__JOLTDIR__!$JOLTDIR!g" \
	-e "s!__JOLTNAME__!$JOLTNAME!g" \
	-e "s!__PORT__!$PORT!g" \
	$JOLTMONITD/$JOLTSERVICE-$JOLTNAME.monit.tmp > $JOLTMONITD/$JOLTSERVICE-$JOLTNAME.monit

mkdir $JOLTDIR/$JOLTSERVICE-$JOLTNAME/db

rm $JOLTMONITD/$JOLTSERVICE-$JOLTNAME.monit.tmp

